eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8891
spring:
  application:
    name: book-service
  cloud:
    config:
      import-check:
        enabled: false


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
