eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8836
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: book-service
  config:
    import:
      configserver:
        enabled: true
        uri: http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
hello:
  message: Hello new
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'