eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8836
spring:
  application:
    name: book-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

