eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8816
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: feign-client
  cloud:
    config:
      discovery:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
  logging:
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG

